// <auto-generated />
namespace IAS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class StateFormsMod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StateFormsMod));
        
        string IMigrationMetadata.Id
        {
            get { return "201402111509436_StateForms-Mod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
