// <auto-generated />
namespace IAS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class CollenctionRiskNameEdit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CollenctionRiskNameEdit));
        
        string IMigrationMetadata.Id
        {
            get { return "201402132053356_Collenction-RiskName-Edit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
